### ISSUE TITLE
Fuzzy mode doesn't detect 'pure' youtube id's 

### ISSUE THREAD

**Issue by tjallingt** [jmorrell/get-youtube-id#2]
```
var getYouTubeID = require('get-youtube-id');

var id = getYouTubeID("9bZkp7q19f0", {fuzzy: true});
console.log(id); // "9bZkp7q19f0"
```

Is there any specific reason that this doesn't work?
I think it would make sense if the `fuzzy` mode would be an opt-in option and returns the possible video id when there are exactly 11 characters entered.

**Comment by shamas** [comment]
This appears to have been done on purpose. In addition to extracting the id, it also tests that it has youtube in the url, to reduce garbage input I guess.
