### ISSUE TITLE
Does not support Shared urls

### ISSUE THREAD

**Issue by kidequinox** [jmorrell/get-youtube-id#4]
Does not support shared urls.

Example url:
https://www.youtube.com/shared?ci=kKOP79HbtMs

I noticed several libs do not support this and mention that the ID specified in the url is not the actual video ID. 

https://github.com/Zod-/jsVideoUrlParser/issues/20

**Comment by jmorrell** [comment]
🤔 Not sure that even existed when I wrote this 4 years ago.

You're right about the ID. The video ID is `uQFVqltOXRg` in that example. What would you expect to happen given that URL? Return `null`?

**Comment by kidequinox** [comment]
I would like it to return the video ID

**Comment by jmorrell** [comment]
That's an issue though. Currently this is just a function that parses a URL for a video ID, which makes it simple to include both in Node and on the client side.

If we want it to take this shared URL, go out, download the page or hit an API, that's a massive increase in scope, requiring different code paths on client and server, and a *lot* more bundled code for the client side. So I don't think I can support getting a video ID out of a shared URL.

Thanks for bringing this up! I'll make sure it's not pulling out a wrong ID, and clarify the purpose of this library on the README.

**Comment by kidequinox** [comment]
Thanks for your response. I agree. I wish youtube had a more developer friendly setup. Or a simpler api tool that helped us translate there many links.
